USE master
GO

CREATE DATABASE DB_DIBREINN
GO

USE DB_DIBREINN
GO

CREATE TABLE TB_UNIDADE
(
ID_UNIDADE VARCHAR(15) NOT NULL,
CNPJ VARCHAR (20)NOT NUll,
TIPO BIT NOT NULL,
LOGRADOURO VARCHAR (50),
NUM INT,
CEP VARCHAR (20),
COMPLEMENTO VARCHAR(50),
BAIRRO VARCHAR (30),
CIDADE VARCHAR(20),
ESTADO CHAR(2)

-- Chave Prim?ria --
CONSTRAINT PK_TB_UNIDADE_ID_UNIDADE PRIMARY KEY (ID_UNIDADE),
CONSTRAINT UQ_TB_UNIDADE_CNPJ UNIQUE (CNPJ),
)
GO

INSERT INTO TB_UNIDADE (ID_UNIDADE,CNPJ,TIPO,LOGRADOURO,NUM,CEP,COMPLEMENTO,BAIRRO,CIDADE,ESTADO) VALUES  ('SAO PAULO','24655141000/01',1,'Francisco Alvares',37,04403060,'Bloco III','Jardim Luso','SAO PAULO','SP')
GO
INSERT INTO TB_UNIDADE (ID_UNIDADE,CNPJ,TIPO,LOGRADOURO,NUM,CEP,COMPLEMENTO,BAIRRO,CIDADE,ESTADO) VALUES  ('RIO DE JANEIRO','24875141000/01',0,'Av. Beira Mar',2455,02203078,'Pr?ximo a praia','Resende','RIO DE JANEIRO','RJ')
GO

CREATE TABLE TB_PESSOA
(
ID_PESSOA INT IDENTITY(1,1) NOT NULL,
NOME VARCHAR (15),
SOBRENOME VARCHAR (25),
SEXO CHAR (1),
RG VARCHAR (15),
CPF VARCHAR(15),
DATANASC DATE,
TELEFONE VARCHAR(15),
CEL VARCHAR (15),
EMAIL VARCHAR(35),
TIPO CHAR(1),
NEWSLETTER BIT,

-- Chave Prim?ria --
CONSTRAINT PK_TB_PESSOA_ID_PESSOA PRIMARY KEY (ID_PESSOA),
CONSTRAINT UQ_TB_PESSOA_CPF UNIQUE (CPF),
CONSTRAINT CK_CADASTROS_SEXO CHECK (SEXO IN ('F','M'))
)
GO

CREATE TABLE TB_FUNCIONARIO
(
ID_PESSOA INT NOT NULL,
ID_UNIDADE VARCHAR(15),
DEPARTAMENTO VARCHAR (15),
CARGO VARCHAR (30),
SALARIO DECIMAL (10,2),
SENHA VARCHAR(20)

-- Chave Prim?ria --
CONSTRAINT PK_TB_FUCIONARIO_ID_PESSOA PRIMARY KEY (ID_PESSOA),
-- Chave Estrangeira --
CONSTRAINT FK_TB_FUNCIONARIO_ID_PESSOA FOREIGN KEY (ID_PESSOA) REFERENCES TB_PESSOA(ID_PESSOA),
CONSTRAINT FK_TB_FUNCIONARIO_ID_UNIDADE FOREIGN KEY (ID_UNIDADE) REFERENCES TB_UNIDADE(ID_UNIDADE),
CONSTRAINT CK_CADASTROS_SALARIO CHECK (SALARIO >= 0)

)
GO

CREATE TABLE TB_HOSPEDE
(
ID_PESSOA INT NOT NULL,
CPF_NOTA BIT,
N_CARTAO VARCHAR (20)

-- Chave Prim?ria --
CONSTRAINT PK_TB_HOSPEDE_ID_PESSOA PRIMARY KEY (ID_PESSOA)
-- Chave Estrangeira --
CONSTRAINT FK_TB_HOSPEDE_ID_PESSOA FOREIGN KEY (ID_PESSOA) REFERENCES TB_PESSOA(ID_PESSOA)

)
GO



CREATE TABLE TB_ENDERECO
(
ID_PESSOA INT NOT NULL,
LOGRADOURO VARCHAR (50),
NUM INT,
CEP VARCHAR (20),
COMPLEMENTO VARCHAR(50),
BAIRRO VARCHAR (30),
CIDADE VARCHAR(20),
ESTADO CHAR(2),
PAIS VARCHAR (30),

-- Chave Prim?ria --
CONSTRAINT PK_TB_ENDERECO_ID_PESSOA PRIMARY KEY (ID_PESSOA),
-- Chave Estrangeira --
CONSTRAINT FK_TB_ENDERECO_ID_PESSOA FOREIGN KEY (ID_PESSOA) REFERENCES TB_PESSOA(ID_PESSOA),
)
GO

CREATE TABLE TB_QUARTO
(
ID_QUARTO INT IDENTITY(1,1)NOT NULL,
VALOR_DIARIA DECIMAL(10,2),
OCUPADO BIT,
NUMERO INT,
ANDAR VARCHAR(10),
RAMAL VARCHAR (10)

-- Chave Prim?ria --
CONSTRAINT PK_TB_QUARTO_ID_QUARTO PRIMARY KEY (ID_QUARTO)
)
GO



--INSERT INTO TB_PESSOA (NOME, SOBRENOME, SEXO, RG, CPF, DATANASC, TELEFONE, EMAIL, TIPO) VALUES ('Luciano','Lourenco','M','478566310','40107258854','1988/11/28','962269655','lucianolourencoti@gmail.com','F')
--go
--INSERT INTO TB_ENDERECO (ID_PESSOA,LOGRADOURO,NUM,CEP,COMPLEMENTO,BAIRRO,CIDADE,ESTADO) VALUES (1,'Rua A',1,'04403060','Bloco A','Cidade Ademar','SAO PAULO','SP')
--go
--INSERT INTO TB_PESSOA (NOME, SOBRENOME, SEXO, RG, CPF, DATANASC, TELEFONE, EMAIL, TIPO) VALUES ('Matheus','Silva','M','445561320','43566878854','1990/11/15','962269655','matheus@gmail.com','F')
--go
--INSERT INTO TB_ENDERECO (ID_PESSOA,LOGRADOURO,NUM,CEP,COMPLEMENTO,BAIRRO,CIDADE,ESTADO) VALUES (2,'Rua B',22,'04419090','Bloco B','Jardim Mirian','RIO DE JANEIRO','RJ')
--go
--INSERT INTO TB_PESSOA (NOME, SOBRENOME, SEXO, RG, CPF, DATANASC, TELEFONE, EMAIL, TIPO) VALUES ('Taynah','Caram de Morais','f','242061320','413542878854','1991/02/24','91284515','taynah_caram@gmail.com','H')
--go
--INSERT INTO TB_ENDERECO (ID_PESSOA,LOGRADOURO,NUM,CEP,COMPLEMENTO,BAIRRO,CIDADE,ESTADO) VALUES (3,'Rua C',2,'04419090','Bloco C','Vila Joaniza','BELO HORIZONTE','MG')
--go

--INSERT INTO TB_FUNCIONARIO (ID_PESSOA,ID_UNIDADE,DEPARTAMENTO,CARGO,SALARIO,USUARIO,SENHA) VALUES (1,'SAO PAULO','TI','Tecnico Em Informatica',1500.00,'lucianolourencoti@gmail.com','quiksilver')
--go
--INSERT INTO TB_FUNCIONARIO (ID_PESSOA,ID_UNIDADE,DEPARTAMENTO,CARGO,SALARIO,USUARIO,SENHA) VALUES (2,'RIO DE JANEIRO','TI','Gerente de TI',4250.00,'gerente@ti.com.br','gerente')
--go
--INSERT INTO TB_HOSPEDE (ID_PESSOA,CPF_NOTA,NACIONALIDADE,N_PASSAPORTE,N_CARTAO) VALUES (3,1,'Estados Unidos','15452145247','456454x564x5')
--go


-- Inserindo Quarto --

INSERT INTO TB_QUARTO (VALOR_DIARIA,OCUPADO,NUMERO,ANDAR,RAMAL) VALUES (152.33,0,23,'2º','7236')
GO
INSERT INTO TB_QUARTO (VALOR_DIARIA,OCUPADO,NUMERO,ANDAR,RAMAL) VALUES (123.57,0,23,'1º','7221')
GO
INSERT INTO TB_QUARTO (VALOR_DIARIA,OCUPADO,NUMERO,ANDAR,RAMAL) VALUES (10.22,1,23,'15º','7599')
GO



SELECT pe.NOME, pe.SOBRENOME, pe.SEXO, pe.RG, pe.CPF, pe.DATANASC, pe.TELEFONE, pe.EMAIL,func.ID_UNIDADE, func.DEPARTAMENTO, func.CARGO, func.SALARIO, e.LOGRADOURO,e.NUM,e.CEP,e.COMPLEMENTO,e.BAIRRO,e.CIDADE,e.ESTADO
FROM TB_FUNCIONARIO as func 
INNER JOIN TB_PESSOA as pe on pe.ID_PESSOA = func.id_pessoa
INNER JOIN TB_ENDERECO as e on e.ID_PESSOA = pe.ID_PESSOA
go

SELECT * FROM TB_PESSOA

--Inclusão de Funcionario usando o conceito de variavel:
INSERT INTO TB_PESSOA (NOME, SOBRENOME, SEXO, RG, CPF, DATANASC, TELEFONE, EMAIL, TIPO) VALUES ('Leandro','Gaona','M','445566310','418882878854','2000/02/24','91284515','leandro_caram@gmail.com','F')

DECLARE @IdCliente AS INT = @@IDENTITY


INSERT INTO TB_ENDERECO (ID_PESSOA,LOGRADOURO,NUM,CEP,COMPLEMENTO,BAIRRO,CIDADE,ESTADO) VALUES (@IdCliente,'Rua D',502,'04412540','Bloco D','Interlagos','São Paulo','SP')

INSERT INTO TB_FUNCIONARIO (ID_PESSOA,ID_UNIDADE,DEPARTAMENTO,CARGO,SALARIO,SENHA) VALUES (@IdCliente,'SAO PAULO','TI','Engenheiro',5000.00,'quiksilver')
go


SELECT * FROM TB_QUARTO
GO