
-- Opera��es de CRUD para TB_UNIDADE --

-- Exemplo de "Insert" de dados na tabela unidade --
USE DB_DIBREINN
GO
INSERT INTO TB_UNIDADE (NOME,CNPJ,TIPO,LOGRADOURO,NUM,CEP,COMPLEMENTO,BAIRRO,CIDADE,ESTADO) VALUES  ('SAO PAULO I','24655141000/01',1,'Francisco Alvares',37,'04403060','Bloco III','Jardim Luso','S�o Paulo','SP')
INSERT INTO TB_UNIDADE (NOME,CNPJ,TIPO,LOGRADOURO,NUM,CEP,COMPLEMENTO,BAIRRO,CIDADE,ESTADO) VALUES  ('SAO PAULO II','54879651000/45',0,'Kansas',1025,'04253090','N/A','Cup�ce','SAO PAULO','SP')
INSERT INTO TB_UNIDADE (NOME,CNPJ,TIPO,LOGRADOURO,NUM,CEP,COMPLEMENTO,BAIRRO,CIDADE,ESTADO) VALUES  ('RIO DE JANEIRO I','24875141000/01',0,'Av. Beira Mar',2455,'02203078','Proximo a praia','Resende','RIO DE JANEIRO','RJ')
GO
SELECT * FROM TB_UNIDADE

-- Exemplo de "Update" de dados na TB_UNIDADE atrav�s do c�digo da unidade --
UPDATE TB_UNIDADE SET TIPO=0,LOGRADOURO='Bras de Abreu',NUM=21,CEP='04419-090',COMPLEMENTO='Z/S',BAIRRO='Interlagos',CIDADE='S�o Paulo',ESTADO='SP'
WHERE ID_UNIDADE ='SAO PAULO I'
GO
SELECT * FROM TB_UNIDADE


-- Exemplo de "Delete" de dados na TB_UNIDADE atrav�s do c�digo da unidade --
DELETE FROM TB_UNIDADE WHERE ID_UNIDADE='RIO DE JANEIRO I'
SELECT * FROM TB_UNIDADE

-- Exemplo de Busca por "ID_UNIDADE" --
SELECT ID_UNIDADE,CNPJ,TIPO,LOGRADOURO,NUM,CEP,COMPLEMENTO,BAIRRO,CIDADE,ESTADO 
FROM TB_UNIDADE 
WHERE ID_UNIDADE='SAO PAULO I'


-- Opera��es de CRUD para "Pessoa Funcionario" -- 

-- Exemplo de "Insert Completo" de um registro de funcionario --
BEGIN TRANSACTION 

INSERT INTO TB_PESSOA 
(NOME, SOBRENOME, SEXO, RG, CPF, DATANASC, TELEFONE,CEL, EMAIL, TIPO,NEWSLETTER) 
VALUES
('Luciano','Louren�o','M','44.552.231-0','401.072.588-53','1988-11-28','(11)6226-9655','(11)96226-9566','lucianolourecoti@gmail.com','F',1)

DECLARE @idCliente AS INT = @@IDENTITY

INSERT INTO TB_ENDERECO 
(ID_PESSOA,LOGRADOURO,NUM,CEP,COMPLEMENTO,BAIRRO,CIDADE,ESTADO,PAIS) 
VALUES 
(@idCliente,'Av. Cup�ce',2200,'04412-060','Bloco 2 Apt.15 ','Vila Prud�ncia','S�o Paulo','SP','Brasil')

INSERT INTO TB_FUNCIONARIO 
(ID_PESSOA,ID_UNIDADE,DEPARTAMENTO,CARGO,SALARIO,SENHA) 
VALUES 
(@idCliente,'SAO PAULO II','TI','T�cnico em Inform�tica',1400.00,'quiksilver')

	IF @@ERROR <> 0
		BEGIN
		ROLLBACK 
	END
	ELSE
		COMMIT
GO

-- Exemplo de "Update" de um registro de funcionario --
BEGIN TRANSACTION
DECLARE @idCliente INT = 1

UPDATE TB_PESSOA SET SOBRENOME='Ramallho', DATANASC='1989-02-09', TELEFONE='(11)5623-2279',CEL='(11)96235-2222', EMAIL='luciano@gmail.com',NEWSLETTER=0
WHERE ID_PESSOA = @idCliente
UPDATE TB_ENDERECO SET LOGRADOURO='Nome da rua',NUM=12,CEP='00000-000',COMPLEMENTO='n/a',BAIRRO='Cidade de Deus',CIDADE='S�o Paulo',ESTADO='SP',PAIS='Brasil'
WHERE ID_PESSOA = @idCliente
UPDATE TB_FUNCIONARIO SET ID_UNIDADE='SAO PAULO I',DEPARTAMENTO='TI',CARGO='Gerente de TI',SALARIO=4500.50,SENHA='quiksilver2'
WHERE ID_PESSOA= @idCliente

IF @@ERROR <> 0
		BEGIN
		ROLLBACK 
	END
	ELSE
		COMMIT
GO


-- Exemplo de "Delete" de um registro de funcionario atrav�s do c�digo --
BEGIN TRANSACTION 
DECLARE @idCliente INT = 1

DELETE  FROM TB_FUNCIONARIO WHERE ID_PESSOA = @idCliente
DELETE  FROM TB_ENDERECO WHERE ID_PESSOA = @idCliente
DELETE  FROM TB_PESSOA WHERE ID_PESSOA = @idCliente

IF @@ERROR <> 0
		BEGIN
		ROLLBACK 
	END
	ELSE
		COMMIT
GO

-- Exemplo de "SELECT" de todos registros de funcionarios --
SELECT PE.ID_PESSOA,pe.NOME, pe.SOBRENOME, pe.SEXO, pe.RG, CPF, pe.DATANASC, pe.TELEFONE, pe.CEL, pe.EMAIL, pe.TIPO,pe.NEWSLETTER,
func.ID_UNIDADE, func.DEPARTAMENTO, func.CARGO, func.SALARIO, 
e.LOGRADOURO,e.NUM,e.CEP,e.COMPLEMENTO,e.BAIRRO,e.CIDADE,e.ESTADO,e.PAIS
FROM TB_FUNCIONARIO as func 
INNER JOIN TB_PESSOA as pe on pe.ID_PESSOA = func.id_pessoa
INNER JOIN TB_ENDERECO as e on e.ID_PESSOA = pe.ID_PESSOA
Go

-- Exemplo de "SELECT" de um registro de funcionario --
SELECT pe.NOME, pe.SOBRENOME, pe.SEXO, pe.RG, CPF, pe.DATANASC, pe.TELEFONE, pe.CEL, pe.EMAIL, pe.TIPO,pe.NEWSLETTER,
func.ID_UNIDADE, func.DEPARTAMENTO, func.CARGO, func.SALARIO, 
e.LOGRADOURO,e.NUM,e.CEP,e.COMPLEMENTO,e.BAIRRO,e.CIDADE,e.ESTADO,e.PAIS
FROM TB_FUNCIONARIO as func 
INNER JOIN TB_PESSOA as pe on pe.ID_PESSOA = func.id_pessoa
INNER JOIN TB_ENDERECO as e on e.ID_PESSOA = pe.ID_PESSOA WHERE pe.CPF='401.072.588-53'
GO


-- Opera��es de CRUD para TB_QUARTO --



-- Exemplo de "Insert" TB_QUARTO --
INSERT INTO TB_QUARTO 
(VALOR_DIARIA,OCUPADO,NUMERO,ANDAR,RAMAL) 
VALUES 
(152.33,0,23,'2�','7236')

INSERT INTO TB_QUARTO 
(VALOR_DIARIA,OCUPADO,NUMERO,ANDAR,RAMAL)
 VALUES 
 (123.57,0,23,'1�','7221')

INSERT INTO TB_QUARTO 
(VALOR_DIARIA,OCUPADO,NUMERO,ANDAR,RAMAL) 
VALUES 
(10.22,1,23,'15�','7599')
GO

GO
-- Exemplo de "Update" TB_QUARTO --
UPDATE TB_QUARTO SET VALOR_DIARIA=10000.50,OCUPADO=1,NUMERO=1502,ANDAR='25�',RAMAL='45380'
WHERE ID_QUARTO= 3
GO
SELECT * FROM TB_QUARTO
GO

-- Exemplo de "Delete" TB_QUARTO --
DELETE TB_QUARTO WHERE ID_QUARTO=6
GO
SELECT * FROM TB_QUARTO
GO

-- Exemplo de "Select" TB_QUARTO atrav�s do ID_QUARTO --
SELECT VALOR_DIARIA,OCUPADO,NUMERO,ANDAR,RAMAL FROM TB_QUARTO WHERE ID_QUARTO=1
GO



Select * from TB_PESSOA
Select * from TB_ENDERECO
Select * from TB_FUNCIONARIO
Select * from TB_HOSPEDE


Delete  from TB_ENDERECO
Delete  from TB_FUNCIONARIO
Delete  from TB_HOSPEDE
Delete from TB_PESSOA



-- Exemplo de "SELECT" de todos registros de Hospede --
SELECT pe.ID_PESSOA,pe.NOME, pe.SOBRENOME, pe.SEXO, pe.RG, CPF, pe.DATANASC, pe.TELEFONE, pe.CEL, pe.EMAIL, pe.TIPO,pe.NEWSLETTER,
e.LOGRADOURO,e.NUM,e.CEP,e.COMPLEMENTO,e.BAIRRO,e.CIDADE,e.ESTADO,e.PAIS,hosp.N_CARTAO,
func.ID_UNIDADE, func.DEPARTAMENTO, func.CARGO, func.SALARIO
FROM TB_PESSOA as pe
INNER JOIN TB_HOSPEDE as hosp on hosp.ID_PESSOA = pe.ID_PESSOA
INNER JOIN TB_ENDERECO as e on e.ID_PESSOA = hosp.ID_PESSOA
INNER JOIN TB_FUNCIONARIO as func on func.ID_PESSOA = e.ID_PESSOA
Go


SELECT max(ID_PESSOA) as ID_PESSOA FROM TB_PESSOA

SELECT ID_PESSOA FROM TB_PESSOA WHERE ID_PESSOA =24


SELECT ID_PESSOA,TIPO FROM TB_PESSOA WHERE CPF= '401.072.588-53'

SELECT * from TB_PESSOA where ID_PESSOA = 43


SELECT pe.NOME, pe.SOBRENOME, pe.SEXO, pe.RG, CPF, pe.DATANASC, pe.TELEFONE, pe.CEL, pe.EMAIL, pe.TIPO,pe.NEWSLETTER,
func.ID_UNIDADE, func.DEPARTAMENTO, func.CARGO, func.SALARIO
FROM TB_FUNCIONARIO as func 
INNER JOIN TB_PESSOA as pe on pe.ID_PESSOA = func.id_pessoa Where func.ID_PESSOA =43

GO